ludviglundgren/qbittorrent-cli

cmd/add.go

Add flags:
- `--paused` - add torrent in paused state
- `--skip_checking` - skip hash check
- `--save-path` - set custom save path for torrent
- `--category` - set category for torrent

Implement more flags for add torrent

---

.qbt.toml.example
README.md
cmd/add.go
internal/config/config.go
internal/domain/config.go
pkg/qbittorrent/domain.go
pkg/qbittorrent/methods.go

Implement rules for better torrent management.
* `enabled` - True/False. Turn on or off.
* `max_active_downloads` - set how many active downloads there can be
* `skip-rules` - Ignore rules from config

Implement rules

---

README.md
cmd/add.go

Set upload and download speed limits on add torrent.

Set speed limits on add torrent

---

README.md
cmd/add.go

Use correct util to convert uint to string.

Fix torrent speed limits

---

.goreleaser.yml
README.md
cmd/import.go
cmd/qbt/main.go
go.mod
go.sum
internal/importer/deluge.go
internal/importer/deluge_test.go
internal/importer/rtorrent.go
internal/importer/rtorrent_test.go
pkg/qbittorrent/fastresume.go
pkg/torrent/torrent.go

Add importer that can import torrents with state from rTorrent.

Import from rTorrent

---

internal/importer/deluge.go
internal/importer/deluge_test.go
internal/importer/rtorrent.go

Refactor deluge import.
- Add dry-run

Refactor deluge import

---

cmd/add.go
pkg/qbittorrent/methods.go

Add additional reannounce delay.

Add additional reannounce delay

---

pkg/qbittorrent/methods.go

fix: resume and pause

---

README.md
cmd/compare.go
cmd/compare_test.go
cmd/qbt/main.go
go.mod
go.sum
pkg/qbittorrent/domain.go
pkg/qbittorrent/methods.go

Compare and get duplicates between two clients.

Feature: Compare client data

---

.gitignore
cmd/edit.go
cmd/qbt/main.go
go.mod

Edit fastresume data with pattern. Useful to change save-path.

Feature: Edit fastresume data

---

.goreleaser.yml
cmd/qbt/main.go
cmd/version.go

Add support for windows and macos.

build: fix versioning and build for windows and macos

---

README.md

docs: add edit cmd

---

cmd/edit.go

Parse fastresume, replace save path then encode file.

Refactor: parse file instead of string replace

---

cmd/add.go
cmd/compare.go
cmd/list.go
cmd/move.go
cmd/pause.go
cmd/qbt/main.go
cmd/resume.go

patch for qbt version work without config

config not required for some commands

---

cmd/list.go

Improved the list command by making the spacing better, making it easier to read, and adding additional information
Things added:
- Shows upload speed or download speed depending on if seeding/leeching
- Shows amount uploaded
- Added days to `Time Active`
- Added torrent hash
- Added indentation for make it easier to read
- Use go.humanize for bytes
Preview of changes:

Feature: improve list cmd design, and add additional information

---

cmd/import.go

Improve log message when running with `--dry-run`.
Fixes #49

feat(import): improve log message for dry-run

---

cmd/move.go

Implement `exclude-tags` for move command.

feat(move): implement exclude-tags

---

cmd/reannounce.go

fix(reannounce): add missing reannounce handler

---

.github/workflows/test.yml
cmd/export.go
cmd/export_test.go
internal/importer/rtorrent_test.go
pkg/qbittorrent/fastresume.go

Fix tests and add test workflow.
Fixes #44

fix(importer): tests

---

internal/config/config.go
pkg/qbittorrent/methods.go

fix: set cookieurl

---

cmd/add.go
cmd/edit.go
cmd/export.go
cmd/import.go
cmd/reannounce.go

fix: code cleanup

---

cmd/add.go
cmd/export.go
cmd/list.go
cmd/move.go
cmd/reannounce.go
cmd/remove.go
pkg/qbittorrent/client.go
pkg/qbittorrent/domain.go
pkg/qbittorrent/methods.go

General refactoring and improvements.
* Return errors instead of log.Fatal
* Try make methods similar
* Pass url.Values where it makes sense

refactor: qbit methods

---

cmd/list.go

fix(list): hashes colliding short flag

---

cmd/export.go
cmd/export_test.go
cmd/torrent_export.go
internal/fs/dir.go

Always compare hashes in lowercase form.

fix(export): improve matching

---

cmd/qbt/main.go
cmd/update.go
go.mod
go.sum

feat: add self-update command

---

README.md

docs: self-update command

---

cmd/torrent_pause.go
cmd/torrent_remove.go
cmd/torrent_resume.go

Add helper method to batch common requests.

feat: batch pause resume remove

---

cmd/torrent_remove.go

Filter torrents to remove by:
- state filter
- category
- include and exclude tags

feat(remove): improve filtering

---

README.md
cmd/torrent.go
cmd/torrent_tracker.go
go.mod
go.sum

feat(torrent): edit trackers

---

README.md

docs: update export command

---

README.md
cmd/torrent_add.go

This should probably be generalized and using the scheme to determine how to handle files in a generic way but this was all I needed.

feat: add torrents from http(s) links
