ludviglundgren/qbittorrent-cli

.qbt.toml.example, cmd/add.go, internal/config/config.go, internal/domain/config.go, pkg/qbittorrent/client.go, pkg/qbittorrent/domain.go, pkg/qbittorrent/methods.go
This adds a reannounce check when adding torrents for trackers that are bugged and won't work directly.
And some additional refactoring of the client.
=> Add reannounce for bugged trackers

README.md, cmd/add.go
⚠️  **Only supported in Qbittorrent 4.3.2+**
Add tags when adding torrents. Supports multiple tags.
```
qbt add file.torrent --tags linux,iso
```
=> Add tags when adding torrents

README.md, cmd/import.go, internal/fs/copy.go
Backup data of source client and qBittorrent before running import.
Will create backup dirs in `~/qbt_backup` for both source client and qBittorrent.
Add flag `--skip-backup`
=> Backup data before import

internal/importer/deluge.go, pkg/qbittorrent/fastresume.go
Add support for older clients.
Tested with:
- `Deluge 1.3.15` -> `qBittorrent 4.2.5`
- `Deluge 1.3.15` -> `qBittorrent 4.3.3`
- `rTorrent 0.9.6` -> `qBittorrent 4.2.5`
- `rTorrent 0.9.6` -> `qBittorrent 4.3.3`
=> Improve import support from older clients

cmd/import.go, go.mod, go.sum
Instead of copying the state directories, create compressed archives instead.
Will create `.tar.gz` archives for source and qbit directories.
=> Backup to compressed archive

cmd/list.go, pkg/qbittorrent/domain.go
Fantastic project you have here, its been super helpful lately! I felt like the qbt list was pretty hard to read so I decided to try and write some of my first Go code to help out!
Screenshot of this PR's current changes (excuse the torrent choices):
These were the properties I found useful to actually be listed, but if you think there are more I missed or something I should remove let me know!
Lastly, I corrected the json property attached to `DlSpeed` from `dl_speed` to `dlspeed`.
=> Overhaul qbt list command to make it more readable

cmd/hash.go, cmd/qbt/main.go
i dont think support bittorrentv2 magnet/torrent (not tested)
always print newline after hash (not detect interactive terminal) can be improved but want your reaction first
=> qbt hash torrent/magnet to print hash

cmd/qbt/main.go, cmd/remove.go
This adds a command to remove torrents using either the torrents name or hash. For ease of us you can provide a shortened prefix of the name or hash and it will identify the torrent that begins with that prefix. It inherits its case-sensitive behavior from qbittorrents remove endpoint.
The command has two main flags that dictate behavior, `--hashes` and `--names` which will indicate how the command interprets the arguments given, i.e if both flags are present then each argument will be checked against the torrents names and hashes to find matches. `--all` will remove all torrents, and `--delete-files` will specify to delete the files on the hard drive associated with the torrent.
Examples of the command in use:
`qbt remove --hashes a1eb`
`qbt remove --names "Kali Linux"`
`qbt remove …
=> Feature: add "remove" command

cmd/pause.go, cmd/remove.go, cmd/resume.go, pkg/qbittorrent/methods.go
Added the same functionality from newly merged Remove command to Pause & Resume commands.
Same `--hashes --names --all` flags added to both Pause & Resume.
Also did a bit of refactoring of the code to search for torrents using name or hash prefixes, and made it into a method for the qbittorrent client in `methods.go` to be universally used on all of the commands mentioned. `GetTorrentsByPrefixes` accepts a string list of terms to search for, and boolean flags to check against either hashes, names, or both.
( I intend to add categories + tags into these commands with separate functions later :) )
=> Feature: add torrent selection for Pause & Resume commands

README.md, cmd/move.go
Add flag `--include-tags` to `move` command to only move torrents if tag matches.
`--include-tags` takes a comma separated list of tags eg. `tag1,tag2`
=> Feature: Move only included tags

cmd/add.go, cmd/compare.go, cmd/edit.go, cmd/hash.go, cmd/list.go, cmd/move.go, cmd/pause.go, cmd/remove.go, cmd/resume.go, internal/domain/config.go, pkg/qbittorrent/client.go, pkg/qbittorrent/domain.go, pkg/qbittorrent/methods.go
Allows for the `qbt list` command to be filtered to list only the torrents specified by a state argument, like `downloading`.
For example:
`qbt list --filter=active` will list all active torrents currently downloading or uploading.
`qbt list` will continue to list all torrents.
New flags:
* `--filter,-f - takes a single qbit state as filter`
* `--category,-c - takes a single category`
* `--tag,-t - takes a single tag`
* `--hashes,-h - takes one or multiple hashes separated by | pipe: "hash1|hash2"`
Also removed the `uploading` TorrentFilter from `domains.go` since it is not a valid filter for the qbittorrent api, and added the missing `errored` filter.  (https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#get-torrent-list)
Fixes #46
=> Filter qbt list command by torrent state.

README.md, cmd/qbt/main.go
Add reannounce command to reannounce torrents. Provide category, tag and hash to only run on some torrents, or run on all downloading/stalled torrents.
=> feat(reannounce): implement reannounce

cmd/remove.go, pkg/qbittorrent/methods.go
`remove --paused`
`remove --paused --delete-files true` - defaults to false
=> feat(remove): add option to remove paused

cmd/torrent_export.go, cmd/torrent_export_test.go, cmd/torrent_pause.go, cmd/torrent_remove.go, cmd/torrent_resume.go
Write manifest for torrent export which collects affected hashes, categories and tags to later be used in an import from qbit feature.
=> feat(export): write export manifest

cmd/torrent_add.go
As discussed on Discord. Changes the amount of time to sleep between adding torrents to 200ms by default and makes it configurable.
=> feat(add): make sleep time configurable

README.md, cmd/torrent_remove.go
Removing torrents with only a filter being set did not work. Fix this by adding an empty category to be included.
For convenience, I have also added the -f and -c flags that are accepted by`torrent list`.
=> fix(torrent): remove with only filter

internal/config/config.go
On PowerShell / CMD the HOME environment variable is often not defined, so $HOME/.config/qbt will evaluate to C:/.config/qbt instead of C:/\<username\>/.config/qbt as one would expect.
=> fix(config): add Windows home dir path

.gitignore, cmd/torrent_category.go, cmd/torrent_list.go, cmd/torrent_pause.go, cmd/torrent_recheck.go, cmd/torrent_remove.go, cmd/torrent_resume.go, cmd/torrent_tracker.go, pkg/utils/utils.go, pkg/utils/utils_test.go
Add validation for hashes on various commands. It checks for alpha-numeric strings with a certain length. It does however not validate that the hashes actually exists in the client.
Related #94
=> feat: validate hashes

cmd/torrent_export.go, pkg/archive/archive.go, pkg/utils/utils.go
Add fix for export on newer qbittorrent versions which removes the `announce` and `announce-urls` fields from the .torrent file.
Needs some extra checks and testing.
=> fix(export): add missing tracker to .torrent

cmd/torrent_add.go
Improve torrent reannounce handling.
=> feat: improve torrent add reannounce handling

cmd/torrent_add.go
Fixes the issue where torrents added with the `--paused` flag were not added in a paused state as expected on v5+
=> fix(torrent_add): add 'stopped' option

cmd/torrent_reannounce.go
This still allows the use case of not specifying a hash at all and re-announcing all torrents.  I do not know why you would want that, but it was a use case and it still works.
Fixes #116
=> fix(reannounce): fail if hash does not exist

README.md, cmd/torrent_import.go, internal/importer/deluge.go
* Fix typos in README.md
* Remove commented-out code from last refactor
* Move handling of --dry-run to later in the import process, so that it calls `continue` just before the first write happens.
* Add logging to error path
Fixes #114
=> fix(importer): typos, logging and dry run handling

cmd/torrent_add.go
Implement `--stop-condition` on torrent add. Values: `None`, `MetadataReceived` and `FilesChecked`.
Closes #120
=> feat(torrent-add): implement stop condition

cmd/app.go, cmd/bencode.go, cmd/category.go, cmd/qbt/main.go, cmd/tag.go, cmd/torrent_add.go, cmd/torrent_category.go, cmd/torrent_compare.go, cmd/torrent_export.go, cmd/torrent_hash.go, cmd/torrent_import.go, cmd/torrent_list.go, cmd/torrent_pause.go, cmd/torrent_reannounce.go, cmd/torrent_recheck.go, cmd/torrent_remove.go, cmd/torrent_resume.go, cmd/torrent_tag.go, cmd/torrent_tracker.go, cmd/update.go, cmd/version.go, internal/config/config.go
Silence output with global flag `-q` or `--quiet`. Errors are still printed to stderr.
Closes #107
=> feat(cli): silence usage with -q and --quiet

cmd/torrent_add.go
Adds a --recheck flag to the torrent add command. When used together with --paused, the torrent will be force rechecked immediately after being added.
=> feat: add --recheck to torrent add with --paused
